export const ItemDataColumns = [
  {
    id: "code",
    label: "Code",
    minWidth: 140,
  },
  {
    id: "name",
    label: "Name",
    minWidth: 190,
    align: "left",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "companyId",
    label: "Company",
    minWidth: 150,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "categoryId",
    label: "Main Category",
    minWidth: 160,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "subcategoryId",
    label: "Sub Category",
    minWidth: 160,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "unit",
    label: "Unit",
    minWidth: 90,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "purchase",
    label: "Purchase",
    minWidth: 50,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "sale",
    label: "Sale",
    minWidth: 110,
    align: "center",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "sale_shop",
    label: "Sale Shop",
    minWidth: 80,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "in_qty",
    label: "In-Qty",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "out_qty",
    label: "Out-Qty",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "qty",
    label: "Qty",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "addeddate",
    label: "Added Date",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
];
