export const ItemDataColumns = [
  {
    id: "itemcode",
    label: "Item Code",
    minWidth: 140,
  },
  {
    id: "itemname",
    label: "Name",
    minWidth: 190,
    align: "left",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itemcompany",
    label: "Company",
    minWidth: 150,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itemcategory",
    label: "Main Category",
    minWidth: 160,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itemsubcategory",
    label: "Sub Category",
    minWidth: 160,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itemunit",
    label: "Unit",
    minWidth: 90,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itempurchase",
    label: "Purchase",
    minWidth: 110,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itemsale",
    label: "Sale",
    minWidth: 80,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itemqty",
    label: "Qty",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "itemaddeddate",
    label: "Added Date",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
];
