export const ItemData = [
    {
      itemcode: "1N",
      name: "1 QAT NASIR",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "57.00",
      sale: "65.00",
      addeddate: "2022-06-02",
      qty: "8213",
    },
    {
      itemcode: "2N",
      name: "2 qat nasir RS(20)",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "50.00",
      sale: "58.00",
      addeddate: "2022-06-02",
      qty: "38450",
    },
    {
      itemcode: "2NB",
      name: "2 QAT NASIR BIG",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Piece",
      purchase: "54.00",
      sale: "62.00",
      addeddate: "2022-06-02",
      qty: "5000",
    },
    {
      itemcode: "3N",
      name: "3 qat nasir RS(20)",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "53.00",
      sale: "61.00",
      addeddate: "2022-06-02",
      qty: "62526",
    },
    {
      itemcode: "3NB",
      name: "3 QAT nasir RS BIG",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "55.00",
      sale: "63.00",
      addeddate: "2022-06-02",
      qty: "7058",
    },
    {
      itemcode: "CHN",
      name: "CHOKUR NASIR",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "67.00",
      sale: "75.00",
      addeddate: "2022-06-02",
      qty: "6178",
    },
    {
      itemcode: "2KGN",
      name: "2 kg nasir",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Piece",
      purchase: "30.00",
      sale: "35.00",
      addeddate: "2022-06-02",
      qty: "97212",
    },
    {
      itemcode: "MXN",
      name: "MIX FURIT NASIR",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "49.00",
      sale: "57.00",
      addeddate: "2022-06-02",
      qty: "5984",
    },
  
    {
      itemcode: "1IM",
      name: "1 QAT IMTAYZ SW",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "55.00",
      sale: "60.00",
      addeddate: "2022-06-02",
      qty: "1070",
    },
  
    {
      itemcode: "2IM",
      name: "2 QAT IMTYAZ SW",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "50.00",
      sale: "56.00",
      addeddate: "2022-06-02",
      qty: "13340",
    },
  
    {
      itemcode: "2IMN",
      name: "2 QAT IMTYAZ N",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "45.00",
      sale: "54.00",
      addeddate: "2022-06-02",
      qty: "1880",
    },
  
    {
      itemcode: "3IM",
      name: "3 QAT IMTAYZ SW",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "52.00",
      sale: "58.00",
      addeddate: "2022-06-02",
      qty: "5640",
    },
  
    {
      itemcode: "3IMN",
      name: "3 QAT IMTAYZ N",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "47.00",
      sale: "55.00",
      addeddate: "2022-06-02",
      qty: "10960",
    },
  
    {
      itemcode: "2KGIM",
      name: "2 KG IMTYAZ",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "26.00",
      sale: "32.00",
      addeddate: "2022-06-02",
      qty: "9739",
    },
  
    {
      itemcode: "4KGIM",
      name: "4 KG IMTYAZ ",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "32.00",
      sale: "42.00",
      addeddate: "2022-06-02",
      qty: "1939",
    },
  
    {
      itemcode: "4KGIMB",
      name: "4 KG IMTYAZ  BIG",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "40.00",
      sale: "42.00",
      addeddate: "2022-06-02",
      qty: "",
    },
  
    {
      itemcode: "MXIM",
      name: "MIX FURIT IMTYZ SW",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "49.00",
      sale: "56.00",
      addeddate: "2022-06-02",
      qty: "18615",
    },
  
    {
      itemcode: "MXIMN",
      name: "MIX FURIT IMTYZ New",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "43.00",
      sale: "60.00",
      addeddate: "2022-06-02",
      qty: "14807",
    },
  
    {
      itemcode: "1NB",
      name: "1 QAT NOBEL",
      company: "NOBEL PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "57.00",
      sale: "65.00",
      addeddate: "2022-06-02",
      qty: "10970",
    },
  
    {
      itemcode: "2NOB",
      name: "2 QAT NOBEL",
      company: "NOBEL PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "50.00",
      sale: "58.00",
      addeddate: "2022-06-02",
      qty: "15433",
    },
  
    {
      itemcode: "3NOB",
      name: "3 QAT NOBEL",
      company: "NOBEL PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "52.00",
      sale: "60.00",
      addeddate: "2022-06-02",
      qty: "140",
    },
  
    {
      itemcode: "2KGA",
      name: "2 KG ARSHID",
      company: "ARSHID PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "21.00",
      sale: "33.00",
      addeddate: "2022-06-02",
      qty: "34097",
    },
  
    {
      itemcode: "4KGA",
      name: "4 KG ARSHID ",
      company: "ARSHID PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "28.00",
      sale: "42.00",
      addeddate: "2022-06-02",
      qty: "8505",
    },
  
    {
      itemcode: "CHZ",
      name: "ZAHID CHOKUR",
      company: "ZAHID PKGZ",
      maincat: "carton",
      unit: "Box",
      purchase: "65.00",
      sale: "75.00",
      addeddate: "2022-06-02",
      qty: "20550",
    },
  
    {
      itemcode: "SH",
      name: "SHOPING",
      company: "IRSHAD PKGS",
      maincat: "SHOPPING",
      unit: "No.",
      purchase: "200.00",
      sale: "220.00",
      addeddate: "2022-06-02",
      qty: "20000600",
    },
  
    {
      itemcode: "PT",
      name: "mix furit pati",
      company: "IRSHAD PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "45.00",
      sale: "55.00",
      addeddate: "2022-07-20",
      qty: "13024",
    },
  
    {
      itemcode: "CHIM",
      name: "IMTYAZ CHOKOR",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "75.00",
      sale: "82.00",
      addeddate: "2022-07-20",
      qty: "9830",
    },
  
    {
      itemcode: "LQI",
      name: "LOQUT IMTYAZ",
      company: "IRSHAD PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "45.00",
      sale: "50.00",
      addeddate: "2022-07-20",
      qty: "9240",
    },
  
    {
      itemcode: "1NN",
      name: "1 qat nasir new",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "64.00",
      sale: "73.00",
      addeddate: "2022-07-20",
      qty: "5120",
    },
  
    {
      itemcode: "2NN",
      name: "2 qat nasir RS(20) new",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "56.00",
      sale: "65.00",
      addeddate: "2022-07-20",
      qty: "6118",
    },
  
    {
      itemcode: "3NN",
      name: "3 qat nasir RS(20) new",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "60.00",
      sale: "68.00",
      addeddate: "2022-07-20",
      qty: "29502",
    },
  
    {
      itemcode: "3NS",
      name: "3 qat nasir RS(s20) new",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "58.00",
      sale: "68.00",
      addeddate: "2022-07-20",
      qty: "38580",
    },
  
    {
      itemcode: "NCHN",
      name: "NASIR CHOKUR new",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "75.00",
      sale: "84.00",
      addeddate: "2022-07-20",
      qty: "3167",
    },
      
    {
      itemcode: "1IMN",
      name: "1 QAT IMTAYZ SW new",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "61.00",
      sale: "68.00",
      addeddate: "2022-07-20",
      qty: "11070",
    },
  
    {
      itemcode: "2IMSN",
      name: "2 QAT IMTYAZ SW new",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "56.00",
      sale: "62.00",
      addeddate: "2022-07-20",
      qty: "3600",
    },
  
    {
      itemcode: "2IMNN",
      name: "2 QAT IMTYAZ N new",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "52.00",
      sale: "60.00",
      addeddate: "2022-07-20",
      qty: "10540",
    },
  
    {
      itemcode: "3IMSN",
      name: "3 QAT IMTAYZ SW new",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "58.00",
      sale: "65.00",
      addeddate: "2022-07-20",
      qty: "7360",
    },
  
    {
      itemcode: "3IMNN",
      name: "3 QAT IMTAYZ N new",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "53.00",
      sale: "60.00",
      addeddate: "2022-07-20",
      qty: "4344",
    },
  
    {
      itemcode: "CHIMN",
      name: "CHOKUR IMTIAZ new",
      company: "IMTYAZ PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "70.00",
      sale: "82.00",
      addeddate: "2022-07-20",
      qty: "1140",
    },
  
    {
      itemcode: "1S",
      name: "1 qat sardar new",
      company: "Sardar pkges",
      maincat: "carton",
      unit: "Box",
      purchase: "68.00",
      sale: "70.00",
      addeddate: "2022-07-22",
      qty: "",
    },
  
    {
      itemcode: "2S",
      name: "2 qat sardar new",
      company: "Sardar pkges",
      maincat: "carton",
      unit: "Box",
      purchase: "58.00",
      sale: "65.00",
      addeddate: "2022-07-22",
      qty: "8480",
    },
  
    {
      itemcode: "3S",
      name: "3 qat sardar",
      company: "Sardar pkges",
      maincat: "carton",
      unit: "Box",
      purchase: "60.00",
      sale: "68.00",
      addeddate: "2022-07-22",
      qty: "7550",
    },
  
    {
      itemcode: "OL",
      name: "OLD",
      company: "IRSHAD PKGS",
      maincat: "OLD BALANCE",
      unit: "Kg",
      purchase: "1.00",
      sale: "1.00",
      addeddate: "2022-07-23",
      qty: "97748730",
    },
  
    {
      itemcode: "3GD",
      name: "3 qat gold",
      company: "IRSHAD PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "58.00",
      sale: "65.00",
      addeddate: "2022-07-27",
      qty: "4434",
    },
    {
      itemcode: "2GD",
      name: "2 qat gold",
      company: "IRSHAD PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "57.00",
      sale: "65.00",
      addeddate: "2022-07-27",
      qty: "8970",
    },
  
    {
      itemcode: "3NBN",
      name: "3 qat NASIR BIG new",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "62.00",
      sale: "70.00",
      addeddate: "2022-07-28",
      qty: "12400",
    },
  
    {
      itemcode: "ZCHN",
      name: "ZAHID CHOKUR new",
      company: "ZAHID PKGZ",
      maincat: "carton",
      unit: "Box",
      purchase: "75.00",
      sale: "84.00",
      addeddate: "2022-07-28",
      qty: "9940",
    },
  
    {
      itemcode: "TNA",
      name: "Tomato Nasir",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "42.00",
      sale: "48.00",
      addeddate: "2022-07-28",
      qty: "9975",
    },
  
    {
      itemcode: "MXZ",
      name: "MIX FURIT ZAHID",
      company: "ZAHID PKGZ",
      maincat: "carton",
      unit: "Box",
      purchase: "55.00",
      sale: "60.00",
      addeddate: "2022-08-01",
      qty: "9980",
    },
  
    {
      itemcode: "LN",
      name: "LOQUT NASIR",
      company: "IRSHAD PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "55.00",
      sale: "60.00",
      addeddate: "2022-08-02",
      qty: "4727",
    },
  
    {
      itemcode: "2NBN",
      name: "2 qat NASIR BIG new",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "61.00",
      sale: "67.00",
      addeddate: "2022-08-13",
      qty: "0",
    },
  
    {
      itemcode: "NPT",
      name: "Nasir persimmon T",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "52.00",
      sale: "62.00",
      addeddate: "2022-09-05",
      qty: "54420",
    },
  
    {
      itemcode: "PNT",
      name: "Nasir persimmon T",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "52.00",
      sale: "62.00",
      addeddate: "2022-09-15",
      qty: "",
    },
  
    {
      itemcode: "PNTA",
      name: "Nasir persimmon T A",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "54.00",
      sale: "64.00",
      addeddate: "2022-09-15",
      qty: "",
    },
  
    {
      itemcode: "PNN",
      name: "Nasir persimmon N",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "58.00",
      sale: "68.00",
      addeddate: "2022-09-15",
      qty: "2000",
    },
  
    {
      itemcode: "PNNA",
      name: "Nasir persimmon N A",
      company: "NASIR PKGS",
      maincat: "carton",
      unit: "Box",
      purchase: "60.00",
      sale: "70.00",
      addeddate: "2022-09-15",
      qty: "",
    },
  ];