export const StockDataColumns = [
  {
    id: "itemId",
    label: "Item Name",
    minWidth: 200,
  },
  {
    id: "purchase",
    label: "Purchase",
    minWidth: 100,
    align: "left",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "qty",
    label: "Qty",
    minWidth: 110,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "total_amount",
    label: "Total",
    minWidth: 80,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "invoice_no",
    label: "Invoice",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "truck_no",
    label: "Truck",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "branch",
    label: "Branch #",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "desc",
    label: "Description",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "date",
    label: "Date",
    minWidth: 100,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
];
